name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        julia-version:
          - '1.7'
          - 'nightly'
        nthreads:
          - '1'
          - '2'
          - '16'
        enable:
          - 'none'
          - 'full'
          - 'recording'
          - 'logging'
          - 'debugging'
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
      - uses: julia-actions/julia-runtest@v1
        env:
          JULIA_NUM_THREADS: ${{ matrix.nthreads }}
          SCHEDULERS_JL_TEST_ENABLE: ${{ matrix.enable }}
          TEST_FUNCTION_RUNNER_JL_TIMEOUT: '120'
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v1
        with:
          file: ./lcov.info
          flags: Pkg.test
          name: codecov-umbrella
  check:
    if: always() && github.event.pull_request
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: "Dump jobs' conclusion"
        run: |
          gh api repos/tkf/Schedulers.jl/actions/runs/${{ github.run_id }}/jobs \
            --jq '.jobs[] | { name, conclusion }'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
      - name: "Check test matrix"
        run: |
          num_non_successes="$(
            gh api repos/tkf/Schedulers.jl/actions/runs/${{ github.run_id }}/jobs \
              --jq '[.jobs[] | .conclusion | select(. != "success")] | length' \
          )"

          echo "num_non_successes = $num_non_successes"
          [ "$num_non_successes" = 0 ]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
